// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: carnival.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	carnival.proto

It has these top-level messages:
	Job
*/
package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Job runs a new job inside the carnival.
type Job struct {
	Body string `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto1.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptorCarnival, []int{0} }

func (m *Job) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto1.RegisterType((*Job)(nil), "proto.Job")
}

func init() { proto1.RegisterFile("carnival.proto", fileDescriptorCarnival) }

var fileDescriptorCarnival = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4e, 0x2c, 0xca,
	0xcb, 0x2c, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x92,
	0x5c, 0xcc, 0x5e, 0xf9, 0x49, 0x42, 0x42, 0x5c, 0x2c, 0x49, 0xf9, 0x29, 0x95, 0x12, 0x5c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x13, 0x7b, 0x14, 0x44, 0x4d, 0x12, 0x1b, 0x98, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xb9, 0x4a, 0xb5, 0x43, 0x00, 0x00, 0x00,
}
